      - name: Commit and push post
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "borak97"
          git config --global user.email "bebo.st88@gmail.com"
          git add posts/
          git commit -m "Add post for $(date +'%Y-%m-%d')" || echo "Nothing to commit"

          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
